In [76]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [77]:
dataset=pd.read_csv('Data.csv')

In [84]:
x = dataset.iloc[:, 0:4].values
y = dataset.iloc[:, 4].values

In [85]:
print(x)

[['Sumba Region - Indonesia' -9.18 nan 10.0]
 ['Banda Sea' -6.55 129.64 10.0]
 ['Java - Indonesia' -7.01 106.63 121.0]
 ...
 ['Flores Sea' -7.83 121.07 92200.0]
 ['Northern Molucca Sea' 3.0 127.16 92201.0]
 ['Sumbawa Region - Indonesia' -8.87 118.95 92202.0]]


In [88]:
print(y)

[4.9 4.6 3.7 ... 3.8 4.1 2.4]


In [91]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:5])
x[:, 1:5] = imputer.transform(x[:,1:5])

In [49]:
print(x)

[[-9.18000000e+00  1.19159384e+02  1.00000000e+01  4.90000000e+00]
 [-6.55000000e+00  1.29640000e+02  1.00000000e+01  4.60000000e+00]
 [-7.01000000e+00  1.06630000e+02  1.21000000e+02  3.70000000e+00]
 ...
 [-7.83000000e+00  1.21070000e+02  9.22000000e+04  3.80000000e+00]
 [ 3.00000000e+00  1.27160000e+02  9.22010000e+04  4.10000000e+00]
 [-8.87000000e+00  1.18950000e+02  9.22020000e+04  2.40000000e+00]]


In [61]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [52]:
print(x_train)

[[-8.3700e+00  1.1622e+02  4.2559e+04  3.1000e+00]
 [-9.8000e+00  1.1287e+02  3.6245e+04  4.0000e+00]
 [ 1.8600e+00  1.2650e+02  8.6510e+04  3.2000e+00]
 ...
 [-1.0150e+01  1.1926e+02  4.9373e+04  3.0000e+00]
 [-9.1100e+00  1.0681e+02  4.5080e+03  3.8000e+00]
 [-6.0400e+00  1.2984e+02  7.7024e+04  4.1000e+00]]


In [54]:
print(x_test)

[[-2.9500e+00  1.1979e+02  4.6284e+04  2.7000e+00]
 [-9.4400e+00  1.2260e+02  5.7118e+04  3.6000e+00]
 [-8.7400e+00  1.1618e+02  1.9450e+04  2.0000e+00]
 ...
 [-7.8200e+00  1.2319e+02  5.6774e+04  3.1000e+00]
 [-8.9700e+00  1.2066e+02  7.8823e+04  2.7000e+00]
 [-1.2400e+00  1.2035e+02  3.1639e+04  3.6000e+00]]


In [55]:
print(y_train)

[3.1 4.  3.2 ... 3.  3.8 4.1]


In [56]:
print(y_test)

[2.7 3.6 2.  ... 3.1 2.7 3.6]


In [ ]:
from sklearn.preprocessing inport StandardScaler as se
sc=se()
x_train[:,]